$.lang = {};
$.lang.en = {
    0: 'A company that helps you make your dreams come true in a virtual space<br>Find you who resembles your dream!',
    1: 'I will live each day <span>AS OWN SELF</span>',
    2: 'Design your <span>DREAM HOUSE</span>',
    3: 'Share your creativity<br> as one of our <span>ARTISTS</span>',
    4: 'Forge wonderful memories with<br>your friends in the <span>METAVERSE WORLD</span>',
    5: 'Experience the magical<br><span>METAVERSE MARKET</span>',
    6: 'A metaverse platform that shares hearts',
    7: 'With beautiful scenery, expansive art exhibitions, and live concerts we invite<br>you to connect with others around the globe, express yourself, and reach for<br>your dreams.',
    8: 'Our passion is to create the go-to "metaverse community"',
    9: 'for artists and art lovers around the globe and offer them<br>opportunities to flourish, grow, and thrive.',
    10: "We've built a realistic metaverse world, and it's developing and growing daily.",
    11: 'Come interact with our elegantly crafted virtual world<br>environments which guarantee new heights in the state-of-the-art<br>metaverse experience.',
    12: 'Introducing the <span>services</span> we are making.',
    13: 'Introducing the <span>business</span> we offer.',
    14: 'When we dream alone, it is only a dream, <br> but when we all dream together, it becomes the beginning of a new world.',
    15: 'Friedensreich Hundertwasser <span>(1928-2000)</span>',
    16: 'Action is the basic key to success.',
    17: 'Pablo Picasso<span>(1881-1973)</span>',
    18: 'When we travel to unfamiliar places,<br>not to see a new world<br> To open your eyes to the world.',
    19: 'Marcel Proust<span>(1871-1922)</span>',
    20: 'Introducing <span>the members</span> who are making this wonderful world.',
    21: 'My avatar in the metaverse.<br>My real persona created by my pure imagination.',
    22: 'MY ME is your personal avatar in the Metaverse. Each <span>my me</span> has an icon above the head that connects to their MY Space.',
    23: 'Approach another <span>my me</span> user will trigger their icon to appear.<br> If you press their icon, it will take you to their MY Space.',
    24: 'You can opt to display your <span>my me</span> in the Metaverse as an NPC, even after logging out.',
    25: 'Top <span>my me</span> influencers can receive top exposure in the Metaverse, implemented with our state-of-the-art robot AI operating system.',
    26: 'A place where I express myself through Lifelogging.',
    27: 'Basic space is provided free of charge.',
    28: 'Items, music, space expansion, etc.<br>Can be purchased with MAUM goods in the service There is.',
    29: 'Their various stories you can include text, photos, audio, video, etc. There is.<br>It is a lifelogging service that allows you to communicate with your friends.',
    30: "The more communication such as 'favorite', 'like', 'comment' and 'share', the more My Space becomes a more attractive hot spot.",
    31: 'Concept can be explained through text, audio and video.<br>NFT minting, gallery exhibition and sale of works created or owned by me.',
    32: 'The exclusive "Artist" gallery. Invite your family and friends to your gallery by sharing the link or QR.<br>Receive likes, comments and feedback about the artwork you show.',
    33: 'The extra exclusive "Special Artist" and "Special Collector" gallery.<br>The artist or a docent My Me can take the role of a Curator.<br>The extra exclusive "Special Gallery" offers a premium spot for maximum exposure.',
    34: 'We create a better world where experiences are shared and cherished,<br> and where your imagination can become reality.',
    35: 'In metaverse space A new way to communicate and<br>experience It is a <span>Social Platform.</span>',
    36: "The artist's works are produced in a metaverse NFT version.",
    37: 'platform',
    38: 'service',
    39: "Global Metaverse' + 'NFT Art' Market Platform",
    40: 'Through the infrastructure, talented writers<br>We help you grow as a global artist.',
    41: 'Realistic Space',
    42: 'Increase immersion with realistic and<br>realistic three-dimensional space expression',
    43: 'Stylish Space',
    44: 'Instead of a childish character or implementation,<br>a space that matches the dignity of the artist and work is realized.',
    45: "Realization of the artist's world",
    46: "Fully realizing the artist's world with a deep understanding<br> of the artist and his work",
    47: 'Innovative exhibition experience',
    48: 'Metaverse + Video + Sound',
    49: 'We examine the characteristics of media in the metaverse space.<br>We aim to display the works of artists according to their intentions by making the most of them.',
    50: 'Artist',
    51: 'About the artist',
    52: 'Studio',
    53: 'About the studio',
    54: 'Sale of works',
    55: 'Introduction and sale of individual works',
    56: 'Context',
    57: "Introduction of the artist's work with a deep understanding",
    58: 'Concept',
    59: "Introducing the artist's world of work",
    60: 'Communication',
    61: 'Communicate with global customers and activate the community',
    62: 'Helping to expand the world of art<br>with NFT technology',
    63: 'Innovation in the NFT art market',
    64: 'By combining the original collection value and the infinite expansion function of digital content,<br>A leader in the art market that will revolutionize the art market',
    65: 'Linking existing works<br> of artists with NFT',
    66: 'Authenticate works by linking existing works of artists with NFT',
    67: 'Digitalization of works<br> in NFT',
    68: 'All digital works owned by the artist are NFTized to protect intellectual re-election rights and increase sales opportunities',
    69: 'NFT-IP integrated <br>management',
    70: 'Ensuring the rights of writers through legal advice',
    71: 'Art product planning <br>and proposal',
    72: 'Target customized art product planning through data analysis and suggestions',
    73: 'our ledership',
    74: 'Intellectual Property Management',
    75: "International lawyer and world-class art appraiser<br>We provide professional Legal Advice to protect your artist's IP",
    76: 'Tax law',
    77: 'Intellectual property',
    78: 'law',
    79: 'Global Art Collectors Community',
    80: 'Tax Law + Intellectual Property + Law',
    81: 'Consulting for writers or buyers',
    82: 'Artist',
    83: 'Product',
    84: 'Strength',
    85: 'Competitiveness',
    86: 'Target',
    87: 'Global art collectors community',
    88: 'Responsibility',
    89: 'Trust',
    90: 'Friendly',
    91: 'Innovation',
    92: 'Unlike existing art platforms,<br>we provide a realistic user experience through the promotion<br> of galleries in the metaverse.',
    93: 'Special exhibition experience',
    94: 'Metaverse Exhibition and art platform',
    95: 'SPACE',
    96: 'space without physical restrictions',
    97: 'ARTIST',
    98: 'Remember the exhibition you want to see again',
    99: 'BRANDING',
    100: 'Various promotional strategies',
    101: 'STILL SHOT',
    102: 'Art Museum Promotion',
    103: 'Fantastic Island is a replica of the real Jeju Island. It is a space where fantastic productions also exist',
    104: 'CHANNEL',
    105: 'Kim Yong-ho Solo Exhibition',
    106: '彼岸 (彼岸) in the meaning of the mound beyond the river Pian (彼岸) It is a relative word for the mound on this side in religion or philosophy, i.e. Chaan (此岸: referring to the present world) It means to transcend from the world.',
    // artfair-accordion
    107: 'We provide a hyper-connected metaverse art gallery that crosses the border between virtual and real.',
    108: 'Innovative Art Fair',
    109: 'Metaverse Exhibition and art platform',
    110: 'SPACE',
    111: 'Launch event, media promotion',
    112: 'COMPETITIVENESS',
    113: 'Sales expansion based on brand promotion effect data',
    114: 'EVENT',
    115: 'Collaboration with event agencies and recruitment of experts',
    116: 'BRANDING',
    117: 'Secure corporate customers with reasonable price policy(lock-in strategy)',
    118: 'STILL SHOT',
    119: 'Metaverse Art Fair',
    120: 'Fantastic Island is a replica of the real Jeju Island. It is a space where fantastic productions also exist.',
    121: 'CHANNEL',
    122: 'Virtual Exhibition',
    123: 'Experience the fanstastic virtual exhibition right now!',
    // jeju-accordion
    124: 'Fantastic Island is a replica of the real Jeju Island It is a space where fantastic productions also exist',
    125: 'Jeju Island Rebranding',
    126: 'Metaverse + Jeju + Branding',
    127: 'Heart',
    128: 'heart sharing system',
    129: 'Nature',
    130: 'Reproduce the nature of Jeju Island',
    131: 'Travel',
    132: 'Fantastic way to travel Jeju Island',
    133: 'CONCEPT',
    134: 'Eco-Friendly',
    135: 'Through the metaverse service, Fantastic Island we will focus on sustainability in not only the environment, but also in the cultural, social and human aspects.',
    136: 'Healing',
    137: 'Metaverse Jeju Travel Service Fantastic Issland provides a variety of experiences that are familiar to us.',
    138: 'Travel',
    139: 'Fantastic Island is a metaverse social platform that allows you to feel a new way of communication and experience in a virtual Jeju space.',
    140: 'Experience',
    141: 'In this place where you can get away from your daily life and meet a new self, you can create your own character, decorate your home, meet friends, and engage in various activities that happen in real life.',
    142: 'SPACE',
    143: 'Open world in JEJU',
    144: 'Fantastic Island is a replica of the real Jeju Island. It is a space where fantastic productions also exist.',
    145: 'Forest',
    146: 'Saryeoni Forest in Jeju Island has a warm landscape that is healing just by looking at it.',
    147: 'Sea',
    148: 'Enjoy the sea of Jeju Island',
    149: 'Activity',
    150: 'Enjoy a variety of leisure activities',
    151: 'Festival',
    152: 'We invite you to an exciting festival.',
    153: 'Metaverse exhibition',
    154: 'Experience the fantastic metaverse exhibition',
    155: 'CHANNEL',
    156: 'The Crossing Lab aims to help more people draw their own dreams and connect with people who can share their hearts through the metaverse social platform',
    157: 'CHAPTER',
    158: 'Forest Walk',
    159: 'Farm',
    160: 'Forest'

};
$.lang.ko = {
    // index
    0: '가상의 공간에서 꿈을 이루게 도와주는 회사 네 꿈과 닮아가는 너를 발견해봐!',
    1: '하루를 살더라도 <span>나만의 나로 </span>살거야',
    2: '나만의 <span>드림하우스를</span> 디자인해봐',
    3: '멋진 <span>아티스트로서</span> 내 작품으로 세상과 소통할거야',
    4: '<span>메타버스 공간에서</span> 친구들과 즐거운 추억을 만들어봐',
    5: '마치 마법과도 같은 <span>메타버스 마켓</span>을 경험해봐',
    6: '마음을 나누는 메타버스 플렛폼',
    7: '아름다운 자연공간, 예술작품 전시 그리고 공연을 통해 더 많은 사람들이 자기만의 꿈을 펼치고, <br> 다른 사람들과 연결되어 마음을 나눌 수 있는 메타버스 소셜 플랫폼입니다.',
    8: '메타버스 세상의 미래를 생각합니다.',
    9: '예술을 좋아하는 모든 사용자를 생각하며 많은 아티스트들에게<br> 새로운 기회를 제공하기 위해 노력하고 있습니다.',
    10: '사실적인 메타버스 공간을 구현합니다.',
    11: '가상의 공간에서 인간의 오감을 극대화하여 실제와 유사한 사용자경험을 제공하고,<br> 새로운 해석을 담은 품격있는 공간을 보여줍니다.',
    12: '우리가 만들어가고 있는 <span>서비스</span>를 소개합니다.',
    13: '우리가 제공하는 <span>비즈니스</span>를 소개합니다.',
    14: '혼자서 꿈을 꾸면 오로지 꿈에 그치지만,<br> 우리 모두가 함께 꿈을 꾸면 그것은 새로운 세상의 시작이 된다.',
    15: '프리덴슈라이히 훈데르트바서(1928-2000)',
    16: '행동은 성공의 기본 열쇠입니다.',
    17: '파블로 피카소(1881-1973)',
    18: '우리가 낯선 곳으로 여행을 떠나는 것은,<br> 새로운 세상을 보기 위해서가 아니라<br> 세상을 보는 눈을 뜨기 위해서다.',
    19: '마르셀 프루스트(1871-1922)',
    20: '이 멋진 세계를 만들어가는 <span>멤버들</span>을 소개합니다.',
    // myme-popup
    21: '메타버스 속 나의 아바타.<br>순수한 나의 상상으로 만들어가는 나의 리얼 페르소나.',
    22: '마이미는 메타버스 속 나의 아바타입니다.<br> 내 아바타는 머리위에 마이스페이스로 연결되는 아이콘을 가지고 있습니다.',
    23: '상대 아바타의 일정 거리내로 접근하면, 아이콘에 불이 켜지고 이 아이콘을 누르면 상대방으 스페이스로 이동할 수 있습니다.',
    24: '내 아바타는 로그아웃을 해도 메타버스 공간안에서 NPC로 등장할 수 있습니다.',
    25: "AI 봇 기능을 통해 관심이 있는 아바타들 위주로 메타버스 공간에 등장하게 할 수 있습니다.",
    // myspace-popup
    26: '라이프로깅을 통해 나를 표현하는 곳',
    27: '베이직 스페이스가 무료로 제공됩니다',
    28: '아이템, 음악, 스페이스 확장 등은<br> 서비스 내 MAUM재화로 구매할 수 있습니다',
    29: '자신의 다양한 이야기를 글, 사진, 오디오, 영상 등으로 담을 수 있습니다.',
    30: "'즐겨찾기', '좋아요', '댓글', '공유'등 소통이 많아질수록 마이스페이스는 더 매력적인 핫플레이스가 됩니다.",
    31: '텍스트, 오디오, 영상을 통해 작품의 컨셉 설명 가능.<br> 내가 창작한 작품이나 소장하고 있는 작품 NFT 민팅, 갤러리 전시, 판매가능.',
    32: "아티스트 등급으로 업그레이드 된 사용자에게 제공됩니다.<br>링크나 QR코드를 통해 공유하고 초대할 수 있습니다.<br>'좋아요', '댓글'등 작품에 대한 피드백을 받을 수 있습니다.",
    33: '스페셜 콜렉터, 스페셜 아티스트 등급의 사용자에게 제공됩니다.<br> 도슨트(혹은 작가)가 등장하여 큐레이터 역할을 대행해 줄 수 있습니다.<br>월드의 유명장소에 위치하여 누구나 쉽게 방문할 수 있습니다.',
    34: '서로 따뜻한 마음을 나누고, 더 나은 공동체를 만들기 위한 공간으로,<br> 누구나 간직하고 있는 추억의 공간이자 상상이 현실이 되는 공간입니다.',
    35: '메타버스 공간에서 새로운 방식의 소통과 경험을 느낄 수 있게 해주는 <span>소셜 플랫폼</span>입니다.',
    36: '작가의 작업은 메타버스 NFT버전으로 제작됩니다.',
    37: '플랫폼',
    38: '서비스',
    39: "'세계적인 메타버스' + 'NFT 예술' 마켓 플랫폼",
    40: '우리는 인프라를 통해 재능있는 작가들이<br> 글로벌 아티스트로 성장할 수 있도록 도와드립니다.',
    41: '현실적인 공간',
    42: '현실감, 현장감 있는 입체적인 공간표현으로 몰입감 증대',
    43: '세련된 공간',
    44: '유아적 캐릭터나 구현이 아닌,<br> 작가 및 작품의 품격에 맞는 공간 구현',
    45: '공간 재해석',
    46: '작기 및 작품에 대한 깊은 이해로<br> 작가의 세계를 온전히 구현',
    47: '전시 공간의 혁신적인 방법',
    48: '메타버스 + 영상 + 소리',
    49: '메타버스 가상환경에서 작가들이 자신만의 전시공간을 소유할 수 있게 하며, 작가 자신과 작업실 작품들 소개 등<br>대중과 소통할 수 있는 시스템을 제공하고, 작품 판매도 대행해 주는 서비스입니다.',
    50: '예술가',
    51: '예술가들을 소개합니다.',
    52: '스튜디오',
    53: '작업실을 소개합니다.',
    54: '개별 작품 소개 및 판매',
    55: '예술가들의 개별 작품 소개 및 판매를 돕습니다.',
    56: '작품 소개',
    57: '작가들의 작품을 소개하는 새로운 방식',
    58: '작품 컨셉',
    59: '작가의 작품세계를 소개합니다.',
    60: '커뮤니케이션',
    61: '글로벌 고객과 소통하며 커뮤니티를 활성화합니다.',
    62: 'Meta Art Space는 NFT 기술로 작품세계의 확장을 돕습니다',
    63: 'NFT 예술 마켓의 혁신',
    64: '우리는 작품의 원본 소장 가치와 디지털 콘텐츠의 무한 확장 기능을 결합하여, 미술시장을 혁신할 미술시장의 선두주자입니다.',
    65: '작가들의 기존 작품을 NFT와 연동',
    66: '작가들의 기존 작품을 NFT와 연동하여 작품을 인증합니다.',
    67: '디지털 형태의 작품 NFT화',
    68: '작가가 보유한 모든 디지털 작품을 NFT화 하여 지적 재산권 보호 및 매출의 기회를 증대합니다.',
    69: 'NFT-IP 통합관리 시스템',
    70: '법률 자문을 통한 작가들의 권리를 보장합니다.',
    71: '아트 상품 기획 및 제안',
    72: '데이터 분석을 통한 타겟 맞춤형 아트상품을 기획 및 제안합니다.',
    73: '우리의 역량',
    74: '지적 재산권을 관리합니다.',
    75: '국제 변호사와 세계적인 미술품 감정사가 세법, 지적 재산권, 법률에 관한 것들을 관리해주며<br>작가 혹은 구매자들을 위한 자세한 컨설팅을 제공합니다.',
    76: '세법',
    77: '지적 재산권',
    78: '법률',
    79: '글로벌스 아트 컬렉터스 커뮤니티',
    80: '세법 + 지적 재산권 + 법률',
    81: '글로벌 아트 컬렉터스 커뮤니티를 육성 발전시킬 예정이며,<br> 글로벌 아트 컬렉터스 커뮤니티와 재능 있는 작가들을 연결시켜주는 창구 역할을 할 것입니다.',
    82: '작가',
    83: '상품',
    84: '강점',
    85: '경쟁력',
    86: '제품',
    87: '글로벌스 아트 컬렉터스 커뮤니티',
    88: '책임',
    89: '신뢰',
    90: '친숙한',
    91: '혁신',
    // archiviong-accordion
    92: '우리는 기존 아트 플랫폼과 달리 메타버스 내 갤러리 홍보를 통해<br> 실제와 유사한 사용자 경험을 제공합니다.',
    93: '초월적인 전시 경험',
    94: '메타버스 아트 전시회 제작',
    95: '공간',
    96: '물리적 제약 없는 공간 표현',
    97: '전시 아카이빙',
    98: '다시 보고 싶은 전시들을 새로운 방식으로 기억합니다',
    99: '브랜딩',
    100: '효과적인 홍보와 광고 전략',
    101: '사진들',
    102: '전시 아카이빙',
    103: '판타스틱 아일랜드에서 시간과 공간에 제약없이 보고싶은 전시를 마음껏 기록하고 기억하세요.',
    104: '채널',
    105: '김용호 솔로전',
    106: '현실 너머 진실 담는 사진가 김용호 보이는 것 그대로 담아서는 좋은 사진가가 될 수 없다. 결국 사진이란 어떻게 다르게 보여주느냐의 경쟁이기도 하지만, 궁극적으로는 누가 더 본질을 잡아내느냐 하는 진실 게임인 것이다.',
    // artfair-accordion
    107: '우리는 가상과 현실의 경계를 넘나드는 초연결된 메타버스 아트 갤러리를 제공합니다.',
    108: '혁신적인 아트 페어',
    109: '메타버스 공간의 아트 페어',
    110: '공간',
    111: '제약없는 공간으로 다양한 연출을 허용합니다.',
    112: '판매 전략',
    113: '데이터 기반으로 판매 확대<br> 브랜드 판촉 효과 극대화',
    114: '협업',
    115: '유명한 아트 페어들과 협업하여 진행합니다.',
    116: '브랜딩',
    117: '합리적인 가격정책으로 기업 고객확보',
    118: '사진들',
    119: '메타버스 아트 페어',
    120: '우리는 기존의 아트 페어와는 달리 차별화된 관점으로 상품을 기획합니다.',
    121: '채널',
    122: '가상 공간 아트 페어',
    123: '판타스틱한 아트 페어를 우리와 함께 경험하세요!',
    // jeju-accordion
    124: '판타스틱 아일랜드는 메타버스 제주 공간에서 새로운 방식의 소통과 경험을 느낄 수 있게 해주는 소셜 플랫폼입니다.',
    125: '제주도 리브랜딩',
    126: '메타버스 + 제주 + 새로운 브랜딩',
    127: '마음',
    128: '사람들과 따뜻한 마음을 주고 받아 보세요.',
    129: '자연',
    130: '재해석한 제주도의 멋진 자연을 느껴보세요.',
    131: '여행',
    132: '판타스틱 아일랜드에서만 할 수 있는 환상적인 여행 경험',
    133: '컨셉',
    134: '친환경',
    135: '우리는 메타버스 서비스인 판타스틱 아일랜드를 통해 환경 뿐 아니라 문화적, 사회적, 인간적 측면의 지속가능성에 초점을 맞출 것입니다.',
    136: '힐링',
    137: '메타버스 제주 여행 서비스 판타스틱 아일랜드는 우리에게 익숙한 여행공간을 새롭게 바라볼 수 있게 하는 다채로운 경험을 제공합니다.',
    138: '여행',
    139: '판타스틱 아일랜드는 가상의 제주 공간에서 새로운 소통과 체험을 경험할 수 있는 메타버스 소셜 플랫폼입니다. 이곳에서 일상을 벗어나 새로운 나를 만나보세요.',
    140: '경험',
    141: '이곳은 다양한 분야에서 활약하는 사람들이 모인 또 하나의 공간이며, 그 계기를 통해 서로 더욱 관심을 가지고 가까워지게 되는 장이기도 합니다. 이곳에서 다양하고 따뜻한 이벤트를 통해 함께 소통할 수 있도록 당신을 이곳으로 초대합니다.',
    142: '장소',
    143: '오픈월드 제주',
    144: '판타스틱 아일랜드의 다양한 장소를 소개합니다!',
    145: '숲',
    146: '제주도의 사려니숲을 그대로 재현한 판타스틱 아일랜드의 새로운 숲을 탐험해보세요.',
    147: '바다',
    148: '제주도의 시원한 바다를 가로질러 펼쳐지는 풍경을 감상해보세요.',
    149: '액티비티',
    150: '다양한 스포츠를 즐겨보세요.',
    151: '축제',
    152: '판타스틱 아일랜드에서 다채로운 축제를 즐겨보세요.',
    153: '메타버스 전시회',
    154: '판타스틱 아일랜드에서 환상적인 전시를 경험하세요.',
    155: '채널',
    156: '우리는 메타버스 제주 공간에서 새로운 방식의 소통과 경험을 선사하는 새로운 소셜 플랫폼입니다.',
    157: '장르',
    158: '숲을 거닐다',
    159: '농장',
    160: '숲'
};

function setLanguage(currentLanguage) {
    console.log('setLanguage', arguments);

    $('[data-langNum]').each(function () {
        var $this = $(this);
        $this.html($.lang[currentLanguage][$this.data('langnum')]);
    });
}

$(document).ready(function () {
    // 언어 변경
    $('.language>li').click(function () {
        var lang = $(this).data('lang');
        setLanguage(lang);
    });
})